name: Checkout and Run
on:
  push:
    branches:
      - main
      - master
jobs:
  checkout_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: yarn install

      - name: build and run
        run: yarn run start
